### ISSUE TITLE
Categories- customisation

### ISSUE THREAD

**Issue by peshwar9** [inspireui/beonews#2] opened 2017-07-04 12:23 UTC
Hi- Can you help me to figure out how to do the following:
1) Right now only 10 categories are retrieved by default. How do i change it? I tried adding per_page=20 to WordPressAPI.getCategories function, but it does not seem to work.
2) How can I retrieve details for only selected list of categories (not all from WP site).

Thanks.

**Comment by inspireui** [comment] 2017-07-06 10:24
Hi, thank you for your feedback, the #1 is caused by missing scrollview, we've noted and update on next version. We will also add the params to help config to limit the category show as well.

These will updated on v2.6.

**Comment by peshwar9** [comment] 2017-07-11 12:58
Hi,

I have another issue to report. I get a warning in dev and error in prod due to the following issue: ‘you are manually calling a React.PropTYpes validation function for the ‘textAlign’ prop on <<anonymous>>. This is deprecated and will not work in production with the next major version. You may be seeing this warning due to a third-party prototypes library.'


Please help asap!

Prabhu

**Comment by minhcasi** [comment] 2017-07-12 14:28
Hi Prabhu, the React.PropTYpes is warning is just a minor issue raise by React Native, it will be fix on next v2.6 as well. Thank you!

**Comment by peshwar9** [comment] 2017-07-13 06:04
Hi- Please advise when v2.6 is expected to be released, as I’m on a deadline to release the app I’m working on. Also, since I have already modified the codebase for my requirement, pls advise how I can integrate your code fixes into my version, as I cannot redo all my changes in mew 2.6 version.

thanks,
Prabhu
=====

**Comment by inspireui** [comment] 2017-07-13 14:40
Hi Prabhu, you can send your email and purchased code to our support email to get it soon - support@beostore.io, we are still testing it before delivery.

For the codebase, we suggest to gitbucket to save your daily commit and merge with our new version when have any update.

Thank you!

**Comment by inspireui** [comment] 2017-07-19 02:32
Hi, i'm closing this ticket as these issues are fix on v2.6. Please reopen it if you still have an issue. Thank you

**Closed as completed by inspireui** 2017-07-19 02:32 UTC
Labels: enhancement
