### ISSUE TITLE
Black screen, and error screen after customize the BeoNews app

### ISSUE THREAD

**Issue by jambortamas** [inspireui/beonews#35] opened 2018-01-04 12:47 UTC
Hi!
We already setup the BeoNews app with our WP website, almost everything fine, but 2 error.
This error appear in iOS simulator, after build and run with "react-native run-ios".

Item Purchase Code:
7235d631-6ffd-4e56-8831-43bb2f63fb0d

1. Black screen with horizontal scroll in settings menu.
![screen shot 2018-01-04 at 13 45 14](https://user-images.githubusercontent.com/1607233/34564045-8b2df83c-f155-11e7-8b03-a7ce1adb0deb.png)

2. Red error screen when i click on a post. After i click to "Dismiss (ESC)" on the bottom, the post loaded already.
![screen shot 2018-01-04 at 13 27 51](https://user-images.githubusercontent.com/1607233/34563988-49587658-f155-11e7-8a96-b214589e139c.png)

How we fix this errors?

**Comment by minhcasi** [comment] 2018-01-08 10:16
the black setting screen will be fix on 2.8.1, could you past the URL here then we can check the root cause for the #2 issue - thank you!

**Comment by jambortamas** [comment] 2018-01-08 10:21
The url of the wordpress site: https://imnews.ie

**Comment by jambortamas** [comment] 2018-01-11 10:26
@minhcasi @inspireui Could you solve the #2 issue?

**Comment by sungkhum** [comment] 2018-01-11 20:19
Also please check my url: https://plovpit.com
Having the same issue.
Thanks!

**Comment by inspireui** [comment] 2018-01-12 02:23
@jambortamas @sungkhum we will have a look

**Comment by inspireui** [comment] 2018-01-12 02:24
Hi @sungkhum could i check what the plugins that you use to load the  POPULAR, HOT, TRENDING articles, we may consider to update the app to support these feature on later version

**Comment by sungkhum** [comment] 2018-01-12 03:10
@inspireui Yeah, the plugin is here: https://wordpress.org/plugins/wordpress-popular-posts/
Also I think this issue is fixed with what I posted here https://github.com/inspireui/beonews/issues/36

**Comment by inspireui** [comment] 2018-01-26 15:57
fixed on 2.8.1

**Closed as completed by inspireui** 2018-01-26 15:57 UTC
Labels: bug, Solution
